### ISSUE TITLE
Refactor HTTP Payload

### ISSUE THREAD

**Issue by smizell** [refractproject/refract-spec#24]
There are several issues I see around using payloads as we currently do. Daniel has brought up a big one, which is that content type may be found in several different locations, and sometimes the content type might not even apply to the body of the payload but rather a schema for the body of the payload.

With these things in mind, I'm proposing thinking of it this way, where HTTP Request and Response will inherit from this.

``` markdown
# HTTP Message Payload (Element)

- `attributes`
    - `schema` (Element) - A schema-based element for the content (JSON Schema or Data Structure)
    - `headers` (HTTP Headers)
- `content` (enum) - The body of the HTTP message
    - (string) - Content of the payload as a string
    - (Element) - Element as the content for extensibility

# JSON Schema (Element)

- `element` jsonSchema
- `attributes`
    - `version`
- `content` (object) - A JSON Schema object

# JSON (Element)

- `element` json
- `content` (enum)
    - (null)
    - (string)
    - (number)
    - (boolean)
    - (array)
    - (object)
```

For the `schema` attribute, you can have multiple different kinds of schemas.

For the content, you may have a string (as is currently used for the Asset element) or an element that provides better usability, such as a `json` element. This way you don't have to do things with the JSON or JSON Schema in order to convert it into a string.

``` json
["httpRequest", {}, { "headers": { "Content-Type": "application/json" }},
  "{ \"foo\": \"bar\" }"
]
```

Or you could use it as below. This is a feature, and not necessary, but could make the document a lot friendlier and accessible.

``` json
["httpRequest", {}, { "headers": { "Content-Type": "application/json" }},
  ["json", {}, {}, {
    "foo": "bar"
  }]
]
```

This opens us up to having the ability to have a canonical message element that can be the content of the HTTP payload.

Finally, if necessary, you could have a `multiPart` element to use as the content of the payload. This would be where you would use assets down the road.

cc @zdne

**Comment by danielgtaylor** [comment]
What if I want to describe this message payload using MSON? The MSON would handle both the content and the schema, so this seems like it wouldn't work out so well. Thoughts?

**Comment by zdne** [comment]
@smizell what is the status of this – is it something you are working on right now?

**Comment by smizell** [comment]
@zdne Just up for discussion at the moment.

**Comment by zdne** [comment]
@smizell is this still valid or has it been addressed?

**Comment by smizell** [comment]
I believe so.

https://github.com/refractproject/rfcs/blob/master/text/0002-clarity-api-description.md#clarify-inheritance
