### ISSUE TITLE
Refract Object Key Change Proposal

### ISSUE THREAD

**Issue by smizell** [refractproject/refract-spec#26]
This proposal is for changing how we use object keys in Refract. The examples
below will be for the following JSON representation:

``` json
{
  "foo": "bar"
}
```
## Current Spec

According to the current spec, this is how the example should be represented
in Refract compact form.

``` json
["object", {}, {}, [
  ["string", { "name": "foo" }, {}, "bar"]
]]
```

MSON definition:

``` markdown
# Property Element (Element)
- `meta`
    - `name` (enum, required) - Name of property given
        - (string)
        - (Element)
```
## Proposed: Member element

This is the proposed representation of a key using a member element. We have
actually used this before, but changed from it for what we thought was a simpler
solution. We're finding some issues around what we changed it to, and are
looking to change it back to this to simplify things.

``` json
["object", {}, {}, [
  ["member", {}, {}, {
    "key": ["string", {}, {}, "foo"],
    "value": ["string", {}, {}, "bar"]
  }]
]]
```

MSON Definition:

``` markdown
# Memeber Element (Element)

- `element` member (string, fixed)
- `content`
    - `key` (Element)
    - `value` (Element)
```

cc @zdne @fosrias

**Comment by klokane** [comment]
No problem for me, originnaly I've implemented MemberElement in this way. I will just backport from git, and change test results in drafter according to change.

**Comment by klokane** [comment]
No problem for me, originnaly I've implemented MemberElement in this way. I will just backport from git, and change test results in drafter according to change.

**Comment by klokane** [comment]
No problem for me, originnaly I've implemented MemberElement in this way. I will just backport from git, and change test results in drafter according to change.

**Comment by zdne** [comment]
:+1:

**Comment by danielgtaylor** [comment]
:+1:

**Comment by zdne** [comment]
Closing as the PR #27 was merged
