### ISSUE TITLE
Parse Result namespace Source Map does not account for multiple files

### ISSUE THREAD

**Issue by zdne** [refractproject/refract-spec#42]
In the prism of solving https://github.com/apiaryio/api-blueprint/issues/8 the [source map](https://github.com/refractproject/refract-spec/blob/master/namespaces/parse-result.md#source-map-element) should be not only be capable of holding the location within a file but also be able to identify the file. 

This is currently not the case and should we need it in a future the Source Map element would have to be changed in a backward incompatible way.

**Comment by smizell** [comment]
@zdne This makes sense to me.

**Comment by pksunkara** [comment]
RFC0006 made sure the current source map refract is future-proof for adding multiple file support.

**Comment by smizell** [comment]
Link to RFC0006:
https://github.com/refractproject/rfcs/blob/3d1e16b4441d8bd8354ef400b3d1da6ec0bf75dc/text/0006-file-source-map.md

**Comment by pksunkara** [comment]
I don't think we should close this since we didn't add multiple file support yet. We just made the existing structure future proof.

**Comment by smizell** [comment]
Wish granted :)

**Comment by pksunkara** [comment]
@smizell Should we move this to api-elements repo?

**Comment by smizell** [comment]
Move to API Elements.

**Comment by kylef** [comment]
-> https://github.com/apiaryio/api-elements/issues/26
