### ISSUE TITLE
Media Type for Refract

### ISSUE THREAD

**Issue by honzajavorek** [refractproject/refract-spec#45]
What is recommended Media Type for Refract JSON documents?

**Comment by kylef** [comment]
I'd guess `application/vnd.refract+json`. Perhaps it would make sense to attach the version number to the content type until it reaches 1.0?

**Comment by smizell** [comment]
This is a good question. Don't we need to register it for it to be official? 

Additionally, this bring up another question. Should we require the media type to be versioned, or should we define the version in the actual document?

**Comment by fosrias** [comment]
You don’t have to, but can register vnd. media-types. If you don’t approach this by version in the document, then you have to continuously change the media-type. If you can get around this by version in the the content-type/accept value. Maybe that is what you mean.

**Comment by smizell** [comment]
Note: this is exactly the kind of stuff I want to be thinking about :)

To consolidate things, I see these options (in no particular order).
1. New media type for each version (major headache)
2. Qualifier in accept/content-type header (application/vnd.refract+json;v=1.0.0)
3. Version number in root element of Refract document
4. Special document element that contains version (e.g. `["document, { "version": "1.0.0" }, {}, []]`)

The first two options use the media type and/or content-type/accept header, while the last two use the element in Refract.

**Comment by honzajavorek** [comment]
I think the old [API Blueprint AST uses 2 (qualifier) together with 3-4 (in-document version)](https://github.com/apiaryio/api-blueprint-ast#example-json-serialization).

**Comment by pksunkara** [comment]
I have a small question. If we use qualifier and the user says he wants `v=0.3.0` in the `Accept` header, API blueprint parser is going to give the latest refract version anyway, right?

So, maybe we want to add a special `version` attribute in the top most element of any given refract?

**Comment by smizell** [comment]
> So, maybe we want to add a special version attribute in the top most element of any given refract?

Those are the last two options I listed above. Do you like a version to be in any element (via `meta`) or would you prefer a special element that wraps the entire document where version is an `attribute`?

**Comment by pksunkara** [comment]
I think we should allow version to be in any element (via `meta`) instead of a special element.

**Comment by smizell** [comment]
I'd vote for even ruling out the first two options, going with general media type of `application/vnd.refract+json` BUT this introduces a question... what version is this? Is this "full" refract or "compact" or either/or? :)

**Comment by pksunkara** [comment]
Are we agreed on this?

**Comment by smizell** [comment]
@pksunkara I don't think so yet. I still have questions in my head. Is `application/vnd.refract+json` the full version of Refract? What is the media type for compact? Or embedded?

**Comment by pksunkara** [comment]
How about `application/vnd.refract.compact+json` and `application/vnd.refract.embedded+json`? We can similarly add stuff like this.

**Comment by smizell** [comment]
@pksunkara So `application/vnd.refract+json` is full Refract? Sounds good to me.

**Comment by zdne** [comment]
> application/vnd.refract+json

Let's go with this.

**Comment by freaz** [comment]
Isn't this closed with https://github.com/refractproject/refract-spec/pull/48 ?
